name: Print Hello Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  print_hello:
    runs-on: ubuntu-latest
    env:
      WEB_USERNAME: ${{ secrets.WEB_USERNAME }}
      WEB_PASSWORD: ${{ secrets.WEB_PASSWORD }}
      WEB_TEST: ${{ secrets.WEB_TEST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: python hello.py
