name: Print Hello Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  print_hello:
    runs-on: ubuntu-latest
    env:
      WEB_USERNAME: ${{ vars.WEB_USERNAME }}
      WEB_PASSWORD: ${{ vars.WEB_PASSWORD }}
      WEB_TEST: ${{ secrets.WEB_TEST }}
      WEB_TEST2: ${{ vars.WEB_TEST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Python script
        run: python hello.py
