name: Print Hello Every 1 Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 1 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: python hello.py
